# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-24 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='article/%Y/%m', verbose_name='封面图'),
        ),
    ]
