# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-24 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('starry', '0004_auto_20190524_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('content', models.TextField(verbose_name='内容')),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='文章配图')),
                ('click_nums', models.IntegerField(default=0, verbose_name='阅读量')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='喜爱量')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='BigCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='大分类')),
                ('desc', models.TextField(max_length=100, verbose_name='分类描述')),
            ],
            options={
                'verbose_name': '大分类',
                'verbose_name_plural': '大分类',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='大分类')),
                ('desc', models.TextField(max_length=100, verbose_name='分类描述')),
                ('bigcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starry.BigCategory', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '大分类',
                'verbose_name_plural': '大分类',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starry.Category', verbose_name='分类'),
        ),
    ]
