# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-27 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starry', '0006_auto_20190524_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_bigcategory',
        ),
        migrations.AddField(
            model_name='article',
            name='bigcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='starry.BigCategory', verbose_name='大分类'),
        ),
    ]
