# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-27 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starry', '0007_auto_20190527_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='bigcategory',
        ),
    ]
