# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-29 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starry', '0009_auto_20190528_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
