# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-01 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starry', '0010_auto_20190529_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='click_nums',
        ),
        migrations.AddField(
            model_name='readnum',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starry.Article'),
        ),
    ]
