# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-01 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starry', '0012_auto_20190601_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
