# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-01 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starry', '0013_auto_20190601_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_tail',
            field=models.CharField(default='', max_length=50, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default='', max_length=50, verbose_name='摘要'),
        ),
    ]
