# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-01 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starry', '0014_auto_20190601_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_tail',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='一句话概述'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='摘要'),
        ),
    ]
